// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function CopyPassword(arg1:string):Promise<void>;

export function CreateAccount(arg1:app.AccountInput):Promise<app.AccountSummary>;

export function DeleteAccount(arg1:string):Promise<void>;

export function GeneratePassword(arg1:app.PasswordOptions):Promise<string>;

export function GetAccount(arg1:string):Promise<app.AccountDetail>;

export function GetLockState():Promise<app.LockState>;

export function GetRuntimeStatus():Promise<app.RuntimeStatus>;

export function GetSettings():Promise<app.Settings>;

export function HideWindow():Promise<void>;

export function InitializeVault(arg1:app.InitializeVaultInput):Promise<void>;

export function IsInitialized():Promise<boolean>;

export function ListAccounts():Promise<Array<app.AccountSummary>>;

export function Lock():Promise<void>;

export function OpenWindow():Promise<void>;

export function Quit():Promise<void>;

export function RecordActivity():Promise<void>;

export function SearchAccounts(arg1:string):Promise<Array<app.AccountSummary>>;

export function Unlock(arg1:app.UnlockInput):Promise<void>;

export function UpdateAccount(arg1:string,arg2:app.AccountInput):Promise<app.AccountSummary>;

export function UpdateSettings(arg1:app.Settings):Promise<void>;
