// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyPassword(arg1) {
  return window['go']['app']['App']['CopyPassword'](arg1);
}

export function CreateAccount(arg1) {
  return window['go']['app']['App']['CreateAccount'](arg1);
}

export function DeleteAccount(arg1) {
  return window['go']['app']['App']['DeleteAccount'](arg1);
}

export function GeneratePassword(arg1) {
  return window['go']['app']['App']['GeneratePassword'](arg1);
}

export function GetAccount(arg1) {
  return window['go']['app']['App']['GetAccount'](arg1);
}

export function GetLockState() {
  return window['go']['app']['App']['GetLockState']();
}

export function GetRuntimeStatus() {
  return window['go']['app']['App']['GetRuntimeStatus']();
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function HideWindow() {
  return window['go']['app']['App']['HideWindow']();
}

export function InitializeVault(arg1) {
  return window['go']['app']['App']['InitializeVault'](arg1);
}

export function IsInitialized() {
  return window['go']['app']['App']['IsInitialized']();
}

export function ListAccounts() {
  return window['go']['app']['App']['ListAccounts']();
}

export function Lock() {
  return window['go']['app']['App']['Lock']();
}

export function OpenWindow() {
  return window['go']['app']['App']['OpenWindow']();
}

export function Quit() {
  return window['go']['app']['App']['Quit']();
}

export function RecordActivity() {
  return window['go']['app']['App']['RecordActivity']();
}

export function SearchAccounts(arg1) {
  return window['go']['app']['App']['SearchAccounts'](arg1);
}

export function Unlock(arg1) {
  return window['go']['app']['App']['Unlock'](arg1);
}

export function UpdateAccount(arg1, arg2) {
  return window['go']['app']['App']['UpdateAccount'](arg1, arg2);
}

export function UpdateSettings(arg1) {
  return window['go']['app']['App']['UpdateSettings'](arg1);
}
